
  clone:
    depth: full

  image: node:20.11.0
  pipelines:
    branches:
      main:
        - step:
            name: Install Node.js 20 and dependencies
            script:
              - npm install
              
        - step:
            name: Run SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-scan:2.0.0

        - step:
            name: Build Project
            script:
              - npm install
              - npm run build
              
        - step:
            name: Zip .next Folder
            script:
              - apt-get update && apt-get install -y zip
              - zip -r website.zip .next/
              
        - step:
            name: Deploy to Netlify
            deployment: production
            script:
              - |
                curl -H "Content-Type: application/zip" \
                   -H "Authorization: Bearer nfp_oEEdNxckaew7wrUAS8WoAb3xC8bTX8Pf3249" \
                   --data-binary "@website.zip" \
                   https://api.netlify.com/api/v1/sites/getyourguide.netlify.app/deploys

    pull-requests:
      '**':
        - step:
            name: Run SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-scan:2.0.0
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.6