clone:
  depth: full

image: node:20.11.0

pipelines:
  branches:
    main:
      - step:
          name: Run SonarCloud
          script:
            - pipe: sonarsource/sonarcloud-scan:2.0.0

      - step:
          name: Prepare Files for Deployment
          script:
            - chmod +x devops/after_install.sh
            - tar -czvf build.tar.gz -T devops/bundle.conf
          artifacts:
            - build.tar.gz

      - step:
          name: Deployment
          image: amazon/aws-cli
          script:
            - aws s3 cp build.tar.gz s3://$S3_BUCKET/bundles/
            - |
              aws deploy create-deployment \
                --application-name $APPLICATION_NAME \
                --deployment-config-name $DEPLOYMENT_CONFIG_NAME \
                --deployment-group-name $DEPLOYMENT_GROUP_NAME \
                --file-exists-behavior OVERWRITE \
                --s3-location bucket=$S3_BUCKET,bundleType=tgz,key=bundles/build.tar.gz
