
  clone:
    depth: full

  image: node:20.11.0
  pipelines:
    branches:
      main:
        - step:
            name: Install Node.js 20 and dependencies
            script:
              - npm install
            artifacts:
              - .node_modules/**              
        # - step:
        #     name: Run SonarCloud
        #     script:
        #       - pipe: sonarsource/sonarcloud-scan:2.0.0

        - step:
            name: Build Project & Zip
            script:
              - npm install
              - npm run build
            artifacts:
              - out/**


        - step:
            name: Zip .next Folder
            script:
              - apt-get update && apt-get install -y zip
              - zip -r website.zip out/
            artifacts:
              - website.zip

        - step:
            name: Deploy to Netlify
            deployment: production
            script:
              - |
                curl --location 'https://api.netlify.com/api/v1/sites/getyourguide.netlify.app/deploys' \
                  --header 'Content-Type: application/zip' \
                  --header 'Authorization: Bearer nfp_oEEdNxckaew7wrUAS8WoAb3xC8bTX8Pf3249' \
                  --data '@website.zip'

    pull-requests:
      '**':
        - step:
            name: Run SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-scan:2.0.0

