
  clone:
    depth: full

  image: node:20.11.0

  pipelines:
    branches:
      main:
        
        # - step:
        #     name: Run SonarCloud
        #     script:
        #       - pipe: sonarsource/sonarcloud-scan:2.0.0

        - step:
            name: Create Scripts
            script:
              # Create before_install.sh script
              - echo '#!/bin/bash' > before_install.sh
              - echo 'sudo lsof -ti :3000 | xargs sudo kill -9' >> before_install.sh  # Replace 3000 with your port number
              
              # Create after_install.sh script
              - echo '#!/bin/bash' > after_install.sh
              - echo 'cd /path/to/your/project' >> after_install.sh
              - echo 'next start > /dev/null 2>&1 &' >> after_install.sh  # Restart the server

              # Make scripts executable
              - chmod +x before_install.sh
              - chmod +x after_install.sh

            artifacts:
              - before_install.sh
              - after_install.sh

        - step:
            name: Install Dependencies & Build Project
            script:
              - npm install
              - npm run build
              - mkdir build
              - mkdir -p build/scripts # Create Scripts folder
              - cp before_install.sh after_install.sh build/scripts #Copy scripts to build folder
              - cp appspec.yml build/ #Copy appspec to build folder
              - cp -r .next build/ #Copy .next to build folder
              - tar -czvf build.tar.gz build
            artifacts:
              - build.tar.gz


        - step:
            name: Deployment
            image: amazon/aws-cli
            script:
            - aws s3 cp build.tar.gz s3://$S3_BUCKET/bundles/
            - |
              aws deploy create-deployment \
                --application-name $APPLICATION_NAME \
                --deployment-group-name $DEPLOYMENT_GROUP_NAME \
                --file-exists-behavior OVERWRITE \
                --s3-location bucket=$S3_BUCKET,bundleType=tgz,key=bundles/build.tar.gz

        #
        # - step:
        #     name: Deploy to Netlify
        #     deployment: production
        #     script:
        #       - |
        #         curl -H "Content-Type: application/zip" \
        #            -H "Authorization: Bearer nfp_oEEdNxckaew7wrUAS8WoAb3xC8bTX8Pf3249" \
        #            --data-binary "@website.zip" \
        #            https://api.netlify.com/api/v1/sites/getyourguide.netlify.app/deploys

    pull-requests:
      '**':
        - step:
            name: Run SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-scan:2.0.0





  # clone:
  #   depth: full

  # image: node:20.11.0
  # pipelines:
  #   branches:
  #     main:
  #       - step:
  #           name: Install Node.js 20 and dependencies
  #           script:
  #             - npm install
  #           artifacts:
  #             - .node_modules/**              
  #       # - step:
  #       #     name: Run SonarCloud
  #       #     script:
  #       #       - pipe: sonarsource/sonarcloud-scan:2.0.0

  #       - step:
  #           name: Build Project & Zip
  #           script:
  #             - npm install
  #             - npm run build
  #           artifacts:
  #             - out/**


  #       - step:
  #           name: Zip .next Folder
  #           script:
  #             - apt-get update && apt-get install -y zip
  #             - zip -r website.zip out/
  #           artifacts:
  #             - website.zip

  #       - step:
  #           name: Deploy to Netlify
  #           deployment: production
  #           script:
  #             - |
  #               curl -H "Content-Type: application/zip" \
  #                  -H "Authorization: Bearer nfp_oEEdNxckaew7wrUAS8WoAb3xC8bTX8Pf3249" \
  #                  --data-binary "@website.zip" \
  #                  https://api.netlify.com/api/v1/sites/getyourguide.netlify.app/deploys

  #   pull-requests:
  #     '**':
  #       - step:
  #           name: Run SonarCloud
  #           script:
  #             - pipe: sonarsource/sonarcloud-scan:2.0.0

